### PR TITLE
 Add the function of calculating dihedral angle, and pass the test 

### PR DESCRIPTION
**Pull request by bagayang**
When I git push origin dihedral_angle_test, and see from my page is 5 files changed ,but when I pull request, it change to  6 files changed. The new file is .gitignore .
The list is the history of today

>   701  cd windows_docs/_github/ppap4lmp/
  702  git fetch upstream
  703  git merge upstream/master
  704  git checkout master
  705  git branch -A
  706  git branch -a
  707  git branch --delete dihedral_angle_test
  708  git branch -D dihedral_angle_test
  709  git branch -a
  710  git checkout -b dihedral_angle_test
  711  git fetch upstream
  712  git merge upstream/master
  713  git checkout master
  714  git fetch upstream
  715  git merge upstream/master
  716  git merge --help
  717  git fetch upstream
  718  git merge upstream/master
  719  git push origin master
  720  git branch -a
  721  git branch -D dihedral_angle_test
  722  git checkout -b dihedral_angle_test
  723  git push origin dihedral_angle_test
  724  git fetch upstream
  725  git merge upstream/master
  726  git push origin dihedral_angle_test
  727  pip install --user -e .
  728  cd tests/tests_adder/
  729  python test_AddDihedralAngle.py
  730  cd ..
  731  git add -A
  732  git commit
  733  git push origin dihedral_angle_test
  734  git commit --amend
  735  git push origin dihedral_angle_test
  736  history

### CODE REVIEW

**Comment by irisTa56** [comment]
You merged upstream/master to the repository you created (i.e. dihedral_angle_test). I recommend merging upstream/master always and only to your master. If you'd like to update your non-master branch, you should merge *your* updated master or create a new branch from the updated master.

Anyway, it seems that using `--amend` option solves the problem, thank you.

In `.gitignore`, the last line break has been removed. Did you notice it?

**Comment by irisTa56** [comment]
> I merge my master and then create the new branch before, but it has error yesterday

Could you explain the error in more detail?

> In `.gitignore`, I don't think it has been changed.

But the file was actually changed. Did you open the file before commit?

**Comment by bagayang** [comment]
Maybe I used the wrong word.It's not a error,but it's strange that many files had been modified. 
This may be because I used the command `git rebase origin/master` when I updated my master.

I didn't open this file . Before I push, the git history and commit page only show 5 files had been modified. It showed 6 changed files only in pull&request page.

The list is the history of the day before yesterday.

> 627  git checkout dihedral_angle_test
  628  git branch -a
  629  cd tests/tests_adder/
  630  python test_AddDihedralAngle.py
  631  cd ..
  632  pip install --user -e .
  633  cd tests/tests_adder/
  634  python test_AddDihedralAngle.py
  635  cd ..
  636  pip install --user -e .
  637  cd tests/tests_adder/
  638  python test_AddDihedralAngle.py
  639  cd .
  640  cd ..
  641  pip install --user -e .
  642  cd tests/tests_adder/
  643  python test_AddDihedralAngle.py
  644  cd ..
  645  git add -A
  646  git commit
  647  git push origin dihedral_angle_test
  648  cd tests/tests_adder/
  649  python test_AddDihedralAngle.py
  650  cd ..
  651  pip install --user -e .
  652  cd tests/tests_adder/
  653  python test_AddDihedralAngle.py
  654  cd ..
  655  git add -A
  656  git commit
  657  git push origin dihedral_angle_test
  658  cd tests/tests_adder/
  659  python test_AddDihedralAngle.py
  660  git checkout master
  661  git add-A
  662  git add -A
  663  git add -a
  664  git add -A
  665  cd ..
  666  git add -A
  667  git commit
  668  git checkout master
  669  git fetch upstream
  670  git merge upstream/master
  671  pip install --user -e .
  672  git push origin master
  673  git push --help
  674  git push origin master
  675  git pull
  676  git fetch
  677  git merge origin/master
  678  git fetch
  679  git rebase origin/master
  680  git push origin master
  681  git branch -a
  682  git branch -D angle_test
  683  git branch -a
  684  git branch -D dihedral_angle_test
  685  git branch -a
  686  git checkout -b dihedral_angle_test
  687  pip install --user -e .
  688  cd tests/tests_adder/
  689  python test_AddDihedralAngle.py
  690  cd ..
  691  git add -A
  692  git commit
  693  cd windows_docs/_github/ppap4lmp/
  694  git add -A
  695  git commit
  696  git push origin dihedral_angle_test
  697  git push --delete origin dihedral_angle_test
  698  git push origin dihedral_angle_test
  699  cd tests/tests_adder/
  700  python test_AddDihedralAngle.py

**Comment by irisTa56** [comment]
What did you intend by executing `git rebase origin/master`? What was your output of `git rebase origin/master`?

`.gitignore` was changed in [this commit](https://github.com/irisTa56/ppap4lmp/pull/5/commits/464951110f44c8067d77a6df95c33d3741fd3917). I think it is not a problem.

**Comment by irisTa56** [comment]
Since `git rebase` is a command modifying the commit history, I guess my commits were duplicated as your commits. Probably it is better not to use `git rebase` in a forked repository. If you encouter the same error again in doing update, you should try only `git pull` or `git fetch` & `git merge`.

Could you restore the state bofore doing `git rebase` and update again? Here is [a hint](https://www.atlassian.com/git/tutorials/resetting-checking-out-and-reverting).

**Pull request closed without merging**
